version: '3.7'


services:

  db:

    image: mariadb:10.6

    container_name: nextcloud-db

    restart: unless-stopped

    volumes:

      - db_data:/var/lib/mysql

    environment:

      MYSQL_ROOT_PASSWORD: 

      MYSQL_DATABASE: nextcloud

      MYSQL_USER: nextcloud

      MYSQL_PASSWORD: 


  app:

    image: nextcloud

    container_name: nextcloud-app

    restart: unless-stopped

    ports:

      - 8080:80

    volumes:

      - /mnt/nextcloud:/var/www/html

    depends_on:

      - db

    environment:

      MYSQL_DATABASE: 

      MYSQL_USER: 

      MYSQL_PASSWORD: 

      MYSQL_HOST: db


volumes:

  db_data:
